name: Sync GitHub Issues & PRs with Trello

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, closed]

jobs:
  sync_with_trello:
    runs-on: ubuntu-latest
    steps:
      - name: Call Trello API to Create or Move Cards
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          BOARD_ID: "NbN9o1PX"
          BACKLOG_LIST_ID: "67e85a40c3cf1d66b18be19a"
          READY_LIST_ID: "67e8581d93f6ede88f3eb055"
          IN_PROGRESS_LIST_ID: "67e85e230f4199ea09bc38fb"
          IN_REVIEW_LIST_ID: "67ed87a8705bc0ac3bc0d0ce"
          DONE_LIST_ID: "67e8581d93f6ede88f3eb056"
        run: |
          ISSUE_TITLE="$(echo "${{ github.event.issue.title || github.event.pull_request.title }}" | jq -sRr @uri)"
          ISSUE_BODY="$(echo "${{ github.event.issue.body || github.event.pull_request.body }}" | jq -sRr @uri)"
          ISSUE_NUMBER="${{ github.event.issue.number || github.event.pull_request.number }}"
          ISSUE_STATE="${{ github.event.issue.state || github.event.pull_request.state }}"
          ISSUE_ACTION="${{ github.event.action }}"
          CARD_NAME="GitHub #${ISSUE_NUMBER}: ${ISSUE_TITLE}"

          # Debugging output
          echo "ISSUE_TITLE: $ISSUE_TITLE"
          echo "ISSUE_BODY: $ISSUE_BODY"
          echo "ISSUE_NUMBER: $ISSUE_NUMBER"
          echo "ISSUE_STATE: $ISSUE_STATE"
          echo "ISSUE_ACTION: $ISSUE_ACTION"
          echo "CARD_NAME: $CARD_NAME"

          # Validar que las variables necesarias están definidas
          if [[ -z "$TRELLO_API_KEY" || -z "$TRELLO_TOKEN" || -z "$BOARD_ID" ]]; then
            echo "❌ Faltan variables de entorno"
            exit 1
          fi

          # Buscar si ya existe una tarjeta en Trello
          CARD_ID=$(curl -s "https://api.trello.com/1/boards/$BOARD_ID/cards?key=$TRELLO_API_KEY&token=$TRELLO_TOKEN" \
            | jq -r --arg CARD_NAME "$CARD_NAME" '.[] | select(.name==$CARD_NAME) | .id')

          # Si el issue es nuevo, creamos la tarjeta en BACKLOG
          if [[ "$ISSUE_ACTION" == "opened" && -z "$CARD_ID" ]]; then
            curl -X POST "https://api.trello.com/1/cards?key=$TRELLO_API_KEY&token=$TRELLO_TOKEN&idList=$BACKLOG_LIST_ID&name=$CARD_NAME&desc=$ISSUE_BODY"
          # Si el issue cambia de estado, movemos la tarjeta
          elif [[ -n "$CARD_ID" ]]; then
            case "$ISSUE_STATE" in
              "open") LIST_ID=$READY_LIST_ID ;;
              "in progress") LIST_ID=$IN_PROGRESS_LIST_ID ;;
              "review requested") LIST_ID=$IN_REVIEW_LIST_ID ;;
              "closed") LIST_ID=$DONE_LIST_ID ;;
            esac
            curl -X PUT "https://api.trello.com/1/cards/$CARD_ID?key=$TRELLO_API_KEY&token=$TRELLO_TOKEN&idList=$LIST_ID"
          fi
